### PR TITLE
Update localization info

### PR DESCRIPTION
**Pull request by andrii-bodnar**

### CODE REVIEW

**Comment by lirantal** [comment]
Thanks Andrii!

**Review by lirantal — APPROVED** [review]
Looks great, thank you!

**Comment by andrii-bodnar** [comment]
@lirantal also, I would suggest adding a localization badge, but it needs to be [enabled in the Crowdin project settings](https://support.crowdin.com/advanced-project-setup/#badges) first

**Comment by lirantal** [comment]
@andrii-bodnar I just enabled it, thanks!
Do you want to PR it maybe? need to add this to the README:

```
[![Crowdin](https://badges.crowdin.net/nodejs-cli-apps-best-practices/localized.svg)](https://crowdin.com/project/nodejs-cli-apps-best-practices)
```

**Pull request merged**
