### PR TITLE
fix(crowdin): add crowdin missing config file

### PR DESCRIPTION
**Pull request by lzm0x219**
@lirantal Please check for errors.

### CODE REVIEW

**Review by lirantal — APPROVED** [review]

**Comment by lirantal** [comment]
Let's give it a go

**Comment by lzm0x219** [comment]
Still failed, kinda weird...

**Comment by lirantal** [comment]
```
STARTING CROWDIN ACTION
UPLOAD SOURCES
❌ Configuration file doesn't exist. Run the 'crowdin init' to generate configuration skeleton
```

Where does it look for the config file?

When you specify https://github.com/lirantal/nodejs-cli-apps-best-practices/blob/main/.github/workflows/crowdin.yml#L25 maybe it looks for it relative to the github action workflow file?

**Comment by lzm0x219** [comment]
> 

It may be so. can you change it.🤯

**Pull request merged**
